dist: xenial
language: python
python:
  - "3.8"
install:
  - pip install coverage
  - pip install python-coveralls
script:
  - coverage run -m unittest discover tests
  - python -m unittest tests/test_add_line_numbers.py
  - python -m unittest tests/test_remove_empty_lines.py
  - python -m unittest tests/test_process_procedure_declaration.py
  - python -m unittest tests/test_process_procedure_calling.py
  - python -m unittest tests/test_prepare_goto_and_gosub_references.py
  - python -m unittest tests/test_resolve_gosub_references.py
  - python -m unittest tests/test_resolve_goto_references.py
  - python -m unittest tests/test_prepare_variables_references.py
  - python -m unittest tests/test_resolve_variables_references.py
  - python -m unittest tests/test_identifier_uniqueness.py
after_success:
  - coveralls
